### ISSUE TITLE
css居中

### ISSUE THREAD

**Issue by cs11b137** [cs11b137/blog#6]
# css居中
css居中包括水平居中、垂直居中以及水平垂直居中。
### 水平居中
（1）行内元素水平居中
（2）块级元素水平居中
（3）图片元素水平居中
```html
<h1 class="h1">这是一个示例标题。</h1>
<div class="container">
    <p class="p">这是一个示例段落。</p>
</div>
<div class="container">
    <img class="img" src="示例图片.png" />
</div>
```
```css
/* 实现：行内元素水平居中 */
.h1 {
    text-align: center;
}
.container {
    border: 2px dashed #ccc;
    width: 600px;
    height: 400px;
}
/* 实现：块级元素水平居中 */
.p {
    margin-left: auto;
    margin-right: auto;
    width: 8em;
}
/* 实现：图片元素水平居中 */
.img {
    display: block;
    margin-left: auto;
    margin-right: auto;
}
```
### 垂直居中
（1）使用`display:table-cell;vertical-align:middle;`
（2）使用`transform`
```html
<div class="container">
    <p class="p">这是一个示例段落。</p>
</div>
```
```css
/* 方式一：使用display:table-cell;vertical-align:middle; */
.container {
    border: 2px dashed #ccc;
    width: 600px;
    height: 400px;

    display: table-cell;
    vertical-align: middle;
}

/* 方式二：使用transform */
.container {
    border: 2px dashed #ccc;
    width: 600px;
    height: 400px;

    position: relative;
}
.p {
    margin: 0;
    position: absolute;
    top: 50%;
    transform: translate(0, -50%);
}
```
### 水平垂直居中
（1）使用`transform`
（2）使用`flex`
```html
<div class="container">
    <p class="p">这是一个示例段落。</p>
</div>
```
```css
/* 方式一：使用transform */
.container {
    border: 2px dashed #ccc;
    width: 600px;
    height: 400px;

   position: relative;
}
.p {
    margin: 0;
    position: absolute;
    top: 50%;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, -50%);
}

/* 方式二：使用flex */
.container {
    border: 2px dashed #ccc;
    width: 600px;
    height: 400px;

    display: flex;
    align-items: center;
    justify-content: center;
}
.p {
    margin: 0;
}
```
### 总结
实际上，`flex`是可以解决上述所有的水平、垂直或水平垂直居中问题，只是`flex`是较新的
标准，兼容性目前还较低，故而在使用`flex`时需要考虑浏览器的兼容性。
